### ISSUE TITLE
Задание 6

### ISSUE THREAD

**Issue by xenor-arch** [aic513/REPEAT_XAVER#5]
Все работает, кроме вот этого условия
elseif (isset($_POST['clear_form'])||isset($_POST['back'])){
    restart();
}

Я не могу понять,почему не очищает данные GET после перезагрузки страницы

**Comment by xenor-arch** [comment]
Условия:
1)Сделать форму
2)Всё что пришло из формы записать в $_SESSION как новое объявление.
3)Под формой создать вывод всех объявлений, содержащихся в сессии по шаблону:
Название объявления | Цена | Имя | Удалить
4)При нажатии на «название объявления» на экран выводится шаблон объявления как из пункта 1, только в места полей подставляются истинные значения
5)При нажатии на «Удалить», объявление удаляется из сессии

**Comment by MysterGoN** [comment]
Закрываю.
